name: Unit Tests

on: [push, pull_request]
env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.1.app/Contents/Developer

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-test-discovery --enable-code-coverage
    - name: Code coverage on macOS
      if: runner.os == 'macOS'
      uses: maxep/spm-lcov-action@0.3.0
      with:
          output-file: ./coverage/lcov.info
    - name: Code Coverage on Linux
      if: runner.os == 'Linux'
      uses: mattpolzin/swift-codecov-action@0.3.0
